//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhGiang_WebCuoiKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBAIDANG
    {
        public int MABAIDANG { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> NGUOIDANG { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<int> MACHUYENMUC { get; set; }
    
        public virtual tbCHUYENMUC tbCHUYENMUC { get; set; }
        public virtual tbNHANVIEN tbNHANVIEN { get; set; }
    }
}
