//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhGiang_WebCuoiKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGIOHANG
    {
        public string MAGIOHANG { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public Nullable<int> MASANPHAM { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
    
        public virtual tbKHACHHANG tbKHACHHANG { get; set; }
        public virtual tbSANPHAM tbSANPHAM { get; set; }
    }
}
