//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace ThanhGiang_WebCuoiKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbKHACHHANG()
        {
            this.tbGIOHANGs = new HashSet<tbGIOHANG>();
            this.tbHOADONs = new HashSet<tbHOADON>();
        }
    
        public int MAKHACHHANG { get; set; }
        public string HOTEN { get; set; }

        [Required(ErrorMessage = "Ngày sinh là bắt buộc.")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string HINHANH { get; set; }
        public string TIEUSU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbGIOHANG> tbGIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHOADON> tbHOADONs { get; set; }
        public virtual tbNGUOIDUNG tbNGUOIDUNG { get; set; }
        public tbKHACHHANG(int MAKHACHHANG, string HOTEN, string EMAIL)
        {
            this.MAKHACHHANG = MAKHACHHANG;
            this.HOTEN = HOTEN;
            this.EMAIL = EMAIL;
        }
    }
}
