//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhGiang_WebCuoiKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNGUOIDUNG
    {
        public int MANGUOIDUNG { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string EMAIL { get; set; }
        public string VAITRO { get; set; }
    
        public virtual tbKHACHHANG tbKHACHHANG { get; set; }
        public virtual tbNHANVIEN tbNHANVIEN { get; set; }
    }
}
